### ISSUE TITLE
Adding tags in eduardoboucas.com

### ISSUE THREAD

**Issue by x0v** [eduardoboucas/eduardoboucas.com#203]
Hi @eduardoboucas,

I really loved your website built on jekyll. I am planning to reuse your template, it's awesome. 

I have two questions -:

1. Do you plan to add tags for posts in your website ?
2. I am unable to host my website on github pages. Can you take a look [here](https://github.com/x0v/x0v.github.io). On typing x0v.github.io in address bar doesn't load anything.

Pardon me if these are very naive questions, I know nothing on web dev.

Great work anyways

**Comment by x0v** [comment]
I am getting this error on github pages as reported by github support.

```
Fatal: Addressable::URI::InvalidURIError
                    Invalid scheme format: .pageNumber | plus
```

**Comment by eduardoboucas** [comment]
That's because I have moved from Jekyll to 11ty (https://github.com/11ty/eleventy). That means it's no longer supported by GitHub Pages.

Your best bet is to use a version of the repository before I made the change (https://github.com/eduardoboucas/eduardoboucas.com/tree/8d8d458bc9644967ef0219cfa1d6e530f8a7fabd).

Good luck!
